import { StyleSheet } from 'react-native';

export const chat = StyleSheet.create({
    top_menu:{
        width:'100%',
        height:40,
        backgroundColor:'#1b211f',
        padding:5
    },
    menu_icon:{
        width:35,
        height:35,
        marginHorizontal:10
    },
    start:{
        flex:1,
        position:'relative',
        zIndex:1,
        alignItems:'center',
        alignContent:'center'
    },
    start_inner:{
        width:'80%',
        height:'70%',
        margin:'5%'
    },
    start_icon:{
        width:180,
        height:180,
        resizeMode:'contain'
    },
    send:{
        height:70,
        backgroundColor:'#1b211f',
        width:'100%',
        flexDirection:'row'
    },  
    sendinput:{
        color:'#ffffff',
        flex:6
    },
    profilepic:{
        width:50,
        height:50,
        borderRadius:50
    },
    msgusername:{
        marginLeft:10,
        marginTop:10,
        color:'#ffffff',
        fontSize:20
    },
    msgcontent:{
        color:'#ffffff',
        fontSize:20,
        flexWrap:'wrap'
    },
    timestamp:{
        color:'lightblue'
    },
    attachment_button:{
        flex:1,
        backgroundColor:'lightblue',
        borderTopRightRadius:5,
        borderBottomRightRadius:5,
        alignItems:'center',
        justifyContent:'center'
    },
    attachment_thumbnail:{
        width:70,
        height:70,
        resizeMode:'cover',
        margin:5
    }
});