import { StyleSheet } from 'react-native';
import { styles } from './styles';

export const chat = StyleSheet.create({
    top_menu:{
        width:'100%',
        height:44,
        backgroundColor:'#1b211f',
        paddingHorizontal:5,
        paddingBottom:8,
        borderBottomWidth:1,
        borderColor:"grey"
    },
    menu_icon:{
        width:35,
        height:35,
        marginHorizontal:10
    },
    send:{
        position:'absolute',
        height:70,
        paddingLeft:10,
        paddingRight:10,
        backgroundColor:'#1b211f',
        bottom:0,
        left:0,
        right:0,
        flexDirection:'row',
        zIndex:0,
        alignItems:'center'
    },  
    sendinput:{
        color:'#ffffff',
        flex:6
    },
    profilepic:{
        width:40,
        height:40,
        borderRadius:50
    },
    chat_main:{
        height:'100%',
        paddingHorizontal:10,
        paddingBottom:115,
        paddingTop:10,
        paddingLeft:10
    },
    msgusername:{
        marginLeft:10,
        marginTop:5,
        color:styles.text.color,
        fontSize:20
    },
    msgcontent:{
        color:styles.text.color,
        fontSize:20,
        flexWrap:'wrap'
    },
    msgActionmenu:{
        flexDirection:'row',
        height:40,
        backgroundColor:'#561f80',
        borderRadius:5,
        padding:5
    },
    timestamp:{
        color:'#4e4b5c'
    },
    action_button:{
        width:45,
        height:45,
        marginHorizontal:5,
        borderRadius:25,
        alignItems:'center',
        justifyContent:'center'
    },
    action_button_hollow:{
        backgroundColor:'transparent',
        borderWidth:2,
        borderColor:'lightblue'
    },
    action_button_icon:{
        width:25, 
        height:25
    },
    attachment_thumbnail:{
        width:70,
        height:70,
        resizeMode:'cover',
        margin:5,
        borderColor:'white',
        borderWidth:2
    }
});