import { StyleSheet } from 'react-native';

export const chat = StyleSheet.create({
    top_menu:{
        width:'100%',
        height:44,
        backgroundColor:'#1b211f',
        padding:5
    },
    menu_icon:{
        width:35,
        height:35,
        marginHorizontal:10
    },
    start:{
        flex:1,
        position:'relative',
        zIndex:1,
        alignItems:'center',
        alignContent:'center'
    },
    start_inner:{
        width:'80%',
        height:'70%',
        margin:'5%'
    },
    start_icon:{
        width:180,
        height:180,
        resizeMode:'contain'
    },
    send:{
        position:'absolute',
        height:70,
        paddingLeft:10,
        backgroundColor:'#1b211f',
        bottom:0,
        left:0,
        right:0,
        flexDirection:'row',
        zIndex:0
    },  
    sendinput:{
        color:'#ffffff',
        flex:6
    },
    profilepic:{
        width:40,
        height:40,
        borderRadius:50
    },
    chat_main:{
        height:'100%',
        paddingHorizontal:10,
        paddingBottom:115
    },
    msgusername:{
        marginLeft:10,
        marginTop:5,
        color:'#ffffff',
        fontSize:20
    },
    msgcontent:{
        color:'#ffffff',
        fontSize:20,
        flexWrap:'wrap'
    },
    msgActionmenu:{
        flexDirection:'row',
        height:40,
        backgroundColor:'#561f80',
        borderRadius:5,
        padding:5
    },
    timestamp:{
        color:'lightblue'
    },
    attachment_button:{
        flex:1,
        backgroundColor:'lightblue',
        borderTopRightRadius:5,
        borderBottomRightRadius:5,
        alignItems:'center',
        justifyContent:'center'
    },
    attachment_thumbnail:{
        width:70,
        height:70,
        resizeMode:'cover',
        margin:5,
        borderColor:'white',
        borderWidth:2
    }
});